### ISSUE TITLE
Error Json-Ld parse context

### ISSUE THREAD

**Issue by massimolauri** [smart-data-models/data-models#13]
Error Json-Ld parse context, not valid:
ccs/sae
bbox
biodieser ethanol
commercial supply
hybrid electric/diesel
hybrid electric/petrol
rainwater capture
snow/ice
water dam

**Comment by albertoabellagarcia** [comment]
It's been corrected:
ccs/sae
snow/ice
biodiesel ethanol
hybrid electric/diesel
hybrid electric/petrol

Not so clear why bbox is not valid, we keep on working

**Comment by albertoabellagarcia** [comment]
water dam
commercial supply 
rainwater capture 

fixed

**Comment by pchampin** [comment]
The JSON-LD context (https://raw.githubusercontent.com/smart-data-models/data-models/master/context.jsonld) is still invalid, as can be [checked in the JSON-LD playground][1].

The problem is with the `bbox` entry, which is currently :
```
"bbox": {
    "@id": "https://purl.org/geojson/vocab#bbox",
    "@container": "@list", 
    "coordinates": {
        "@id": "https://purl.org/geojson/vocab#coordinates", 
        "@container": "@list"
    }
},
```
and should be
```
"bbox": {
    "@id": "https://purl.org/geojson/vocab#bbox",
    "@container": "@list", 
    "@context": {
        "coordinates": {
            "@id": "https://purl.org/geojson/vocab#coordinates", 
            "@container": "@list"
        }
    }
},
```
I.e., the term definitions for the inner properties of `bbox` can not appear directly in the term definition of `bbox`, they must be in a [scoped `@context`](https://www.w3.org/TR/json-ld/#scoped-contexts).


[1]: https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%22https%3A%2F%2Fraw.githubusercontent.com%2Fsmart-data-models%2Fdata-models%2Fmaster%2Fcontext.jsonld%22%7D
