### ISSUE TITLE
Question : unit of measure

### ISSUE THREAD

**Issue by TOTOleHero** [smart-data-models/data-models#34]
Hello, 

I have some question for all models. How is defined the unit of measure ?

All models defined type number or string, but not explain the unit of measure applied to attribute (km, tonne, kilogramme, hour, format, ....) .

Where is defined ?

Thank's you

Thomas Lecarpentier

**Comment by albertoabellagarcia** [comment]
First thing thanks for the relevant question.
In all the specs (last line, currently) of the data models (see [this example](https://smartdatamodels.org/index.php/ddbb-of-properties-descriptions/)) is explained why are not units included. The summary is that some models have defined the units and some others don't. And in any case, is a recommendation.
In fact, you can search for units in the [search option on the front page](https://smartdatamodels.org/index.php/ddbb-of-properties-descriptions/).
But to give you an example of the implications of setting strictly the units. Imagine that you use device data model and you are measuring temperature and you want to use it on Fahrenheit and other use case is willing to use it in Celsius. 
The philosophy of the Smart Data Models Program is: Make recommendations based on use cases that work in real case scenarios but do not impose barriers for others to use them. Make it easy to interoperate but do not try to impose it because imposing is something we already know that is not working.
