### ISSUE TITLE
Give credits to the original authors and contributors of the FIWARE Data Models

### ISSUE THREAD

**Issue by jmcanterafonseca** [smart-data-models/data-models#7]
Dear Smart Data Models,

You need to give credits in the corresponding repos to the original authors of the FIWARE Data Models that were just copied here. Currently, the authorship has been diluted in new commits made by people who, currently, might be contributors but not the original authors. 

Thank you

**Comment by albertoabellagarcia** [comment]
Definitely. 
Is there a simple way to extract them or just it has to be extracted from every file programming an script againts github API?

**Comment by jason-fox** [comment]
* https://github.com/FIWARE/data-models/graphs/contributors
* https://github.com/smart-data-models/data-models/graphs/contributors

You could probably use the GitHub API to automate it if necessary

**Comment by albertoabellagarcia** [comment]
I did use the GitHub API to recover every transaction and recover the author (not the committer) and to aggregate it across the different data models, then manually update everyone, unfortunately, some cases it was not possible to recover the mil because it is private data in the configuration. And I guess that the organisation of the people are the one they have now, not the one they had when they did the commit. Anyhow it's done.
